Add Python Tests
tschmidtb51/JSON-schema-pattern pull request #4
Opened 2024-11-19 13:08 UTC by lebogg

- [X] Add Python file for testing
- [X] Add GitHub workflow file

2025-02-19 16:24 UTC, bernhardreiter commented
ping @tschmidtb51 , this PR has an example test action so it is more important than the others two.

2025-02-19 21:13 UTC, tschmidtb51 requested changes
Minor comments

2025-02-19 21:13 UTC, tschmidtb51 commented on .github/workflows/tests.yml
> +        uses: actions/checkout@v3
I think we need to use v4 now:
```suggestion
        uses: actions/checkout@v4

2025-02-19 21:13 UTC, tschmidtb51 commented on .github/workflows/tests.yml
> +        uses: actions/setup-python@v4
I think we need to use v5 now:
```suggestion
        uses: actions/setup-python@v5

2025-02-28 08:30 UTC, lebogg commented on .github/workflows/tests.yml
> +        uses: actions/checkout@v3
Done

2025-02-28 08:30 UTC, lebogg commented on .github/workflows/tests.yml
> +        uses: actions/setup-python@v4
Done

2025-02-28 15:07 UTC, tschmidtb51 approved these changes
LGTM

2025-02-28 15:07 UTC, merged